### ISSUE TITLE
Where's the data directory?

### ISSUE THREAD

**Issue by NeoMahler** [thefinn93/SubredditAnnouncer#3]
I don't see the data directory where I have to put the configuration file. Thanks in advanced!

**Comment by thefinn93** [comment]
depends on your supybot config. by default it's called `data/` and is next to your supybot config file

**Comment by NeoMahler** [comment]
Oh, I thought it was in the plugins/SubredditAnnouncer directory. Thanks!

**Comment by NeoMahler** [comment]
Ok, I have another question: is it possible to set up more than one subreddit in the same channel? If I put `subreddits = example1,example2` it says `Checking http://www.reddit.com/r/example1,example2/new.json?sort=new` and then it says `Whoops! Something fucked up: 'data'`. If I make different sections for the same channel and different subreddits, it only checks the last subreddit.

Sorry for flooding you with these issues, but I will appreciate your help! :)

**Comment by thefinn93** [comment]
Ah yes, my highly descriptive error messages! I thought i had an example in the description, but you just `+` instead of `,`. So you do `subreddits = example1+example2`. This just takes advantage of the reddit feature where `/r/example1+example2` is a combination of `/r/example1` and `/r/example2`.

**Comment by NeoMahler** [comment]
Oh! Thank you very much :)
